<script setup lang="ts">
import { useHead } from '@unhead/vue'
import PlaceholderImage from '../components/common/PlaceholderImage.vue'
import { turmas, contraturno } from '../data/turmas'
import { SCHOOL_NAME, SCHOOL_TAGLINE, WHATSAPP_URL } from '../data/contatos'
import { canonicalHead } from '../data/seo'

useHead({ htmlAttrs: { lang: 'pt-BR' }, title: `Turmas e horários | ${SCHOOL_NAME}`, link: canonicalHead('/turmas'), meta: [{ name: 'description', content: `Maternal, Jardim de Infância e Fundamental I na escola Waldorf ${SCHOOL_NAME}, ${SCHOOL_TAGLINE.toLowerCase()} em Nova Iguaçu. Confira horários e contraturno.` }, { property: 'og:title', content: `Turmas e horários | ${SCHOOL_NAME}` }] })
</script>

<template>
  <div class="content-page">
    <section class="page-hero"><div class="container page-hero-grid"><div><span class="eyebrow">Um percurso com cuidado e propósito</span><h1>Turmas para <em>crescer no seu tempo.</em></h1><p>Da primeira infância aos anos iniciais do Fundamental, cada turma vive experiências pensadas para sua fase.</p><p class="page-claim">{{ SCHOOL_TAGLINE }}.</p></div><div class="page-hero-art"><PlaceholderImage label="Ilustração aquarelada de uma escola rodeada por natureza" variant="children" /></div></div></section>
    <section class="section-pad"><div class="container"><div class="section-heading"><span class="eyebrow">Nossos grupos</span><h2>Aprendizagens que acompanham <em>cada etapa.</em></h2></div><div class="class-card-grid detail-class-grid"><article v-for="turma in turmas" :key="turma.name" class="class-card" :class="`tone-${turma.color}`"><span class="class-icon"><i :class="turma.icon" aria-hidden="true"></i></span><span class="eyebrow">{{ turma.age }}</span><h3>{{ turma.name }}</h3><p>{{ turma.description }}</p><div class="class-meta"><span><i class="ri-time-line" aria-hidden="true"></i>{{ turma.schedule }}</span></div><div class="capacity-note"><i class="ri-team-line" aria-hidden="true"></i> Até 10 alunos · professora e auxiliar</div></article></div></div></section>
    <section class="section-pad schedule-section"><div class="container schedule-grid"><div class="section-copy"><span class="eyebrow">Horários regulares</span><h2>Ritmo diário com espaço <em>para cada criança.</em></h2><p>Os horários regulares acompanham as diferentes etapas da escola. Converse conosco para entender qual turma atende melhor sua família.</p><a class="text-link" :href="WHATSAPP_URL" target="_blank" rel="noreferrer">Tire suas dúvidas pelo WhatsApp <i class="ri-arrow-right-line" aria-hidden="true"></i></a></div><div class="schedule-list"><div><span class="schedule-icon"><i class="ri-sun-line" aria-hidden="true"></i></span><strong>Maternal e Jardim</strong><b>08h às 12h30</b></div><div><span class="schedule-icon"><i class="ri-book-open-line" aria-hidden="true"></i></span><strong>Fundamental I · 1º ao 5º ano</strong><b>07h às 12h</b></div><div><span class="schedule-icon"><i class="ri-time-line" aria-hidden="true"></i></span><strong>Horário estendido</strong><b>Opções até 15h ou 18h</b></div></div></div></section>
    <section class="section-pad"><div class="container contraturno-card"><div><span class="eyebrow">Novas descobertas</span><h2>Contraturno para <em>experimentar e criar.</em></h2><p>Atividades extras podem ampliar o repertório das crianças. Consulte a escola sobre disponibilidade, turmas e horários.</p><div class="activity-chips"><span v-for="atividade in contraturno" :key="atividade"><i class="ri-sparkling-line" aria-hidden="true"></i>{{ atividade }}</span></div></div><div class="contraturno-illustration"><i class="ri-palette-line" aria-hidden="true"></i><i class="ri-music-2-line" aria-hidden="true"></i><i class="ri-plant-line" aria-hidden="true"></i></div></div></section>
    <section class="section-pad"><div class="container food-grid"><div class="food-stamp"><i class="ri-leaf-fill" aria-hidden="true"></i><span>Comida<br>de verdade</span></div><div class="section-copy"><span class="eyebrow">Nutrir também é educar</span><h2>Sabores simples, <em>cuidado de todo dia.</em></h2><p>A alimentação prioriza opções naturais, com frutas e legumes, valorizando variedade, bons hábitos e momentos de convivência à mesa.</p></div></div></section>
    <section class="section-pad tuition-section"><div class="container tuition-card"><div><span class="eyebrow">Vamos conversar?</span><h2>Uma proposta de qualidade, com <em>mensalidade competitiva.</em></h2><p>Fale com a equipe para conhecer valores, condições e opções adequadas à sua família.</p></div><a class="button button-primary" :href="WHATSAPP_URL" target="_blank" rel="noreferrer"><i class="ri-whatsapp-line" aria-hidden="true"></i> Consultar pelo WhatsApp</a></div></section>
  </div>
</template>
